'use client';

import Image from 'next/image';
import Link from 'next/link';
import { motion } from 'framer-motion';
import { ArrowLeft, Star, Sparkles, ChevronRight } from 'lucide-react';

interface CentrifugeType {
  id: number;
  name: string;
  image: string;
  imageAlt: string;
  definition: string;
  howItWorks: string;
  applications: string[];
  advantages: string[];
  disadvantages: string[];
  borderColor: string;
  bgColor: string;
  dotColor: string;
}

const centrifugeTypes: CentrifugeType[] = [
  {
    id: 1,
    name: 'Clinical Centrifuge',
    image: '/images/type-clinical-centrifuge.png',
    imageAlt: 'Clinical centrifuge used in hospitals and diagnostic laboratories',
    definition:
      'A clinical centrifuge is a laboratory centrifuge commonly used in hospitals, diagnostic centers, and medical laboratories to separate blood components and other biological fluids. It is one of the most widely used types of centrifuges in healthcare settings due to its reliability, ease of use, and ability to handle routine sample processing tasks efficiently.',
    howItWorks:
      'The operator places blood sample tubes into the rotor, ensuring proper balance. When the machine spins at moderate speeds, the heavier blood cells (red and white cells) move to the bottom of the tube due to centrifugal force, while the lighter plasma remains at the top. This separation allows for clear analysis of individual blood components for diagnostic purposes.',
    applications: [
      'Blood testing and analysis',
      'Urine analysis and sedimentation',
      'Plasma and serum separation',
      'Routine diagnostic procedures',
    ],
    advantages: [
      'Easy to operate with minimal training',
      'Compact size fits on standard lab benches',
      'Reliable for routine clinical tasks',
      'Affordable and cost-effective',
    ],
    disadvantages: [
      'Limited maximum speed capability',
      'Not suitable for high-speed applications',
      'Small sample capacity per run',
      'Basic features with limited programmability',
    ],
    borderColor: 'border-[#4169E1]',
    bgColor: 'bg-blue-50/60',
    dotColor: 'bg-[#4169E1]',
  },
  {
    id: 2,
    name: 'Microcentrifuge',
    image: '/images/type-microcentrifuge.png',
    imageAlt: 'Small microcentrifuge for molecular biology labs',
    definition:
      'A microcentrifuge is a small, compact centrifuge designed for processing very tiny sample volumes, typically ranging from 0.2 mL to 2.0 mL. It is extensively used in molecular biology, biochemistry, and genetics laboratories for rapid separation of small volumes of biological samples, including cells, proteins, and nucleic acids.',
    howItWorks:
      'Microcentrifuges spin at extremely high speeds, often reaching up to 15,000 RPM or more, to generate powerful centrifugal force in a compact space. The high speed causes denser particles such as cells, cell debris, or precipitated proteins to rapidly pellet at the bottom of the microcentrifuge tube, while the supernatant containing the desired biomolecules remains at the top for easy collection.',
    applications: [
      'DNA and RNA extraction protocols',
      'PCR preparation and sample processing',
      'Cell pelleting and harvesting',
      'Protein precipitation and purification',
    ],
    advantages: [
      'Compact size saves bench space',
      'High speed for rapid separations',
      'Ideal for small sample volumes',
      'Quick spin-down capabilities',
    ],
    disadvantages: [
      'Limited to small sample volumes',
      'Not suitable for large-scale processing',
      'Tube capacity is restricted',
      'Limited temperature control options',
    ],
    borderColor: 'border-[#7C3AED]',
    bgColor: 'bg-purple-50/60',
    dotColor: 'bg-[#7C3AED]',
  },
  {
    id: 3,
    name: 'Refrigerated Centrifuge',
    image: '/images/type-refrigerated-centrifuge.png',
    imageAlt: 'Refrigerated centrifuge with cooling system for temperature-sensitive samples',
    definition:
      'A refrigerated centrifuge is equipped with a built-in cooling system that maintains low temperatures within the rotor chamber during operation. This type of centrifuge is essential for processing temperature-sensitive biological samples such as proteins, enzymes, DNA, RNA, and living cells that could degrade or become inactive due to heat generated during high-speed spinning.',
    howItWorks:
      'The refrigerated centrifuge operates similarly to a standard centrifuge but includes a compressor-based cooling system that circulates refrigerant through coils surrounding the chamber. A thermostat monitors the internal temperature and adjusts cooling output to maintain the set temperature, typically ranging from -20 degrees Celsius to +40 degrees Celsius. This ensures that heat generated by friction during rotation is continuously removed, protecting sample integrity.',
    applications: [
      'Protein purification and analysis',
      'Enzyme studies and activity assays',
      'DNA and RNA isolation',
      'Cell culture processing and harvesting',
    ],
    advantages: [
      'Protects temperature-sensitive samples',
      'Enables long-duration centrifugation runs',
      'Prevents heat-induced sample degradation',
      'Wide temperature range for flexibility',
    ],
    disadvantages: [
      'More expensive than standard centrifuges',
      'Higher energy consumption',
      'Requires regular maintenance of cooling system',
      'Heavier and less portable',
    ],
    borderColor: 'border-[#0891b2]',
    bgColor: 'bg-cyan-50/60',
    dotColor: 'bg-[#0891b2]',
  },
  {
    id: 4,
    name: 'High-Speed Centrifuge',
    image: '/images/type-highspeed-centrifuge.png',
    imageAlt: 'High-speed centrifuge for advanced laboratory separations',
    definition:
      'A high-speed centrifuge is designed to operate at significantly higher rotational speeds than standard or clinical centrifuges, typically reaching speeds of 15,000 to 30,000 RPM. These centrifuges generate much greater centrifugal force, enabling the separation of smaller particles such as organelles, viruses, and large macromolecules that cannot be effectively separated at lower speeds.',
    howItWorks:
      'The high-speed centrifuge uses a powerful electric motor and precision-engineered rotor to achieve extreme rotational speeds. As the rotor spins, the intense centrifugal force pushes particles of different densities outward at varying rates based on their mass and the buoyant density of the medium. Smaller, denser particles sediment faster, allowing for detailed fractionation of complex biological mixtures into distinct layers or pellets.',
    applications: [
      'Organelle isolation (mitochondria, nuclei)',
      'Virus purification and concentration',
      'Macromolecule separation',
      'Subcellular fractionation studies',
    ],
    advantages: [
      'Capable of separating very small particles',
      'High g-force for efficient pelleting',
      'Suitable for advanced research applications',
      'Versatile with multiple rotor options',
    ],
    disadvantages: [
      'Requires careful balancing and operation',
      'More expensive than standard models',
      'Generates significant heat during operation',
      'Noise levels can be high at top speeds',
    ],
    borderColor: 'border-[#dc2626]',
    bgColor: 'bg-red-50/60',
    dotColor: 'bg-[#dc2626]',
  },
  {
    id: 5,
    name: 'Ultracentrifuge',
    image: '/images/type-ultracentrifuge.png',
    imageAlt: 'Ultracentrifuge for extremely high-speed molecular separations',
    definition:
      'An ultracentrifuge is the most powerful type of laboratory centrifuge, capable of achieving speeds exceeding 100,000 RPM and generating centrifugal forces over 1,000,000 times the force of gravity. It is used for the most demanding separation tasks in molecular biology, biochemistry, and nanotechnology, including the separation of molecules by size, density, and molecular weight.',
    howItWorks:
      'The ultracentrifuge uses an advanced vacuum system to eliminate air resistance and friction that would otherwise generate excessive heat and limit speed. The rotor spins inside a vacuum chamber at extraordinary speeds, creating centrifugal forces sufficient to separate individual molecules, nanoparticles, and macromolecular complexes. Analytical ultracentrifuges can even monitor separation in real-time using optical detection systems.',
    applications: [
      'Density gradient centrifugation',
      'Molecular weight determination',
      'Nanoparticle separation and characterization',
      'Lipoprotein and membrane protein studies',
    ],
    advantages: [
      'Highest centrifugal force available',
      'Can separate at the molecular level',
      'Extremely precise and reproducible results',
      'Analytical models provide real-time data',
    ],
    disadvantages: [
      'Very expensive to purchase and maintain',
      'Requires specialized training to operate',
      'Time-consuming setup and run preparation',
      'Sensitive to vibration and imbalance',
    ],
    borderColor: 'border-[#0d9488]',
    bgColor: 'bg-teal-50/60',
    dotColor: 'bg-[#0d9488]',
  },
  {
    id: 6,
    name: 'Hematocrit Centrifuge',
    image: '/images/type-hematocrit-centrifuge.png',
    imageAlt: 'Hematocrit centrifuge for blood analysis and packed cell volume',
    definition:
      'A hematocrit centrifuge is a specialized compact centrifuge designed specifically for determining the hematocrit value, which is the percentage of red blood cells in a given volume of whole blood. It uses small capillary tubes instead of standard centrifuge tubes and is a critical tool in clinical hematology for diagnosing conditions such as anemia, polycythemia, and dehydration.',
    howItWorks:
      'The operator fills thin glass or plastic capillary tubes with blood and seals one end. The tubes are placed in the rotor in a radial orientation, and the centrifuge spins at high speed for a short period, typically two to five minutes. The centrifugal force separates the blood into three distinct layers: red blood cells at the bottom, a thin buffy coat of white cells and platelets in the middle, and plasma at the top. A specialized reader then measures the packed cell volume.',
    applications: [
      'Hematocrit (packed cell volume) determination',
      'Anemia screening and diagnosis',
      'Polycythemia detection',
      'Dehydration assessment',
    ],
    advantages: [
      'Quick results within minutes',
      'Simple and straightforward operation',
      'Low cost per test',
      'Compact and portable design',
    ],
    disadvantages: [
      'Limited to blood analysis only',
      'Small sample capacity',
      'Manual reading may introduce error',
      'Capillary tubes are fragile',
    ],
    borderColor: 'border-[#e11d48]',
    bgColor: 'bg-rose-50/60',
    dotColor: 'bg-[#e11d48]',
  },
  {
    id: 7,
    name: 'Benchtop Centrifuge',
    image: '/images/type-benchtop-centrifuge.png',
    imageAlt: 'Benchtop centrifuge for general-purpose laboratory use',
    definition:
      'A benchtop centrifuge is a medium-sized centrifuge designed to sit on a laboratory bench or work surface, offering a balance between capacity, speed, and convenience. It is one of the most versatile types of centrifuges, suitable for a wide range of general-purpose applications in research, clinical, educational, and industrial laboratories. Benchtop centrifuges accommodate various rotor types and tube sizes.',
    howItWorks:
      'The benchtop centrifuge operates by spinning its rotor at controlled speeds using an electric motor. Samples placed in tubes are loaded into the rotor, which can be a fixed-angle, swinging-bucket, or horizontal configuration depending on the application. The centrifugal force generated during spinning causes denser components to migrate outward, effectively separating the sample into distinct fractions based on density differences.',
    applications: [
      'General laboratory sample separation',
      'Cell culture processing',
      'Environmental sample analysis',
      'Quality control testing',
    ],
    advantages: [
      'Versatile for multiple applications',
      'Moderate capacity for various tube sizes',
      'Easy to operate and maintain',
      'Space-efficient benchtop design',
    ],
    disadvantages: [
      'Limited maximum speed compared to floor models',
      'May not have temperature control',
      'Smaller capacity than floor-standing models',
      'Can vibrate at higher speeds on uneven surfaces',
    ],
    borderColor: 'border-[#ea580c]',
    bgColor: 'bg-orange-50/60',
    dotColor: 'bg-[#ea580c]',
  },
  {
    id: 8,
    name: 'Floor-Standing Centrifuge',
    image: '/images/type-floorstanding-centrifuge.png',
    imageAlt: 'Large floor-standing centrifuge for high-capacity laboratory processing',
    definition:
      'A floor-standing centrifuge is a large, heavy-duty centrifuge that rests directly on the laboratory floor rather than on a bench. These centrifuges offer significantly greater capacity, higher speeds, and more advanced features than benchtop models. They are commonly found in high-throughput laboratories, blood banks, pharmaceutical manufacturing, and research institutions that process large volumes of samples daily.',
    howItWorks:
      'The floor-standing centrifuge houses a powerful motor and a large-capacity rotor system capable of holding dozens of sample tubes simultaneously. Advanced models feature microprocessor-controlled speed and temperature regulation, programmable acceleration and deceleration profiles, and multiple rotor options for different applications. The robust construction and heavy base minimize vibration even at maximum speed, ensuring stable and reproducible separations.',
    applications: [
      'High-throughput sample processing',
      'Blood bank plasma separation',
      'Pharmaceutical manufacturing',
      'Large-scale research studies',
    ],
    advantages: [
      'High capacity for large sample volumes',
      'Advanced programmable features',
      'Greater speed and force capabilities',
      'Stable operation with minimal vibration',
    ],
    disadvantages: [
      'Requires significant floor space',
      'Much more expensive than benchtop models',
      'Heavy and difficult to relocate',
      'Higher power consumption',
    ],
    borderColor: 'border-[#4f46e5]',
    bgColor: 'bg-indigo-50/60',
    dotColor: 'bg-[#4f46e5]',
  },
  {
    id: 9,
    name: 'Industrial Centrifuge',
    image: '/images/type-industrial-centrifuge.png',
    imageAlt: 'Heavy-duty industrial centrifuge for large-scale manufacturing',
    definition:
      'An industrial centrifuge is a heavy-duty, large-scale centrifuge designed for continuous or batch processing of large volumes of materials in industrial settings. Unlike laboratory centrifuges that handle small sample tubes, industrial centrifuges process materials in liters or even hundreds of liters per cycle. They are used in industries such as food processing, chemical manufacturing, pharmaceuticals, wastewater treatment, and oil refining.',
    howItWorks:
      'Industrial centrifuges use powerful motors and large-diameter rotors to generate high centrifugal forces on bulk materials. The material is fed continuously or in batches into the spinning bowl or drum, where centrifugal force separates components based on density differences. The separated fractions are discharged through different outlets, with solids collected at the bowl wall and liquids removed through weirs or nozzles. Some models feature continuous discharge for uninterrupted processing.',
    applications: [
      'Food and beverage processing',
      'Chemical and pharmaceutical manufacturing',
      'Wastewater treatment and sludge dewatering',
      'Oil and fuel purification',
    ],
    advantages: [
      'Handles very large volumes efficiently',
      'Continuous operation capability',
      'Robust construction for harsh environments',
      'Automated process control systems',
    ],
    disadvantages: [
      'Very high initial investment cost',
      'Requires specialized installation',
      'Significant maintenance requirements',
      'Large footprint and infrastructure needs',
    ],
    borderColor: 'border-[#65a30d]',
    bgColor: 'bg-lime-50/60',
    dotColor: 'bg-[#65a30d]',
  },
  {
    id: 10,
    name: 'Vacuum Centrifuge',
    image: '/images/type-vacuum-centrifuge.png',
    imageAlt: 'Vacuum centrifuge concentrator for solvent evaporation',
    definition:
      'A vacuum centrifuge, also known as a centrifugal concentrator or speedvac, is a specialized centrifuge that combines centrifugal force with vacuum pressure to rapidly concentrate liquid samples by evaporating solvents. It is widely used in analytical chemistry, drug discovery, proteomics, and environmental analysis for preparing samples before downstream analytical techniques such as HPLC, mass spectrometry, and NMR spectroscopy.',
    howItWorks:
      'The vacuum centrifuge spins samples in a rotor while simultaneously applying a vacuum to the chamber. The combination of centrifugal force, which prevents sample bumping and boiling, and reduced atmospheric pressure from the vacuum, which lowers the boiling point of the solvent, causes rapid and gentle evaporation. Samples are concentrated into a small volume or dried completely without the need for elevated temperatures that could damage heat-sensitive analytes.',
    applications: [
      'Sample concentration for mass spectrometry',
      'Solvent removal for HPLC preparation',
      'Drug discovery and compound screening',
      'Environmental sample concentration',
    ],
    advantages: [
      'Gentle concentration without heating',
      'Prevents sample loss from bumping',
      'Processes multiple samples simultaneously',
      'Preserves heat-sensitive compounds',
    ],
    disadvantages: [
      'Not for particle separation applications',
      'Requires vacuum pump maintenance',
      'Limited to solvent evaporation tasks',
      'Slower than direct heating methods',
    ],
    borderColor: 'border-[#ca8a04]',
    bgColor: 'bg-yellow-50/60',
    dotColor: 'bg-[#ca8a04]',
  },
];

export default function CentrifugeTypesPage() {
  return (
    <div className="min-h-screen bg-gradient-to-b from-[#E6E1FF] via-[#f3e8ff] to-white relative overflow-hidden">
      {/* Background decorative elements */}
      <div className="absolute top-10 right-6 w-24 h-24 rounded-full bg-purple-200/20 pointer-events-none animate-float" />
      <div className="absolute top-40 left-4 w-16 h-16 rounded-full bg-blue-200/15 pointer-events-none animate-float-delayed" />
      <div className="absolute bottom-40 right-10 w-20 h-20 rounded-full bg-purple-300/15 pointer-events-none animate-float" />
      <Star className="absolute top-16 right-14 w-2.5 h-2.5 text-blue-400/30 animate-float" />
      <Star className="absolute top-28 left-12 w-2 h-2 text-purple-300/25 animate-float-delayed" />
      <Sparkles className="absolute top-52 right-8 w-3 h-3 text-blue-300/20 animate-float" />

      {/* Top accent bar */}
      <div className="h-1 bg-gradient-to-r from-[#1a237e] via-[#4169E1] to-[#7C3AED]" />

      {/* Back button */}
      <div className="relative z-10 px-5 sm:px-8 pt-5 pb-2">
        <Link href="/centrifuge/menu">
          <motion.button
            initial={{ opacity: 0, x: -10 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ duration: 0.4 }}
            className="w-9 h-9 rounded-full bg-white shadow-md flex items-center justify-center text-[#4169E1] hover:text-[#1E3A8A] hover:shadow-lg transition-all duration-200 hover:-translate-x-0.5 group"
          >
            <ArrowLeft className="w-4 h-4" />
          </motion.button>
        </Link>
      </div>

      {/* Title */}
      <div className="relative z-10 px-5 sm:px-8 pt-3 pb-4 text-center">
        <motion.h1
          initial={{ opacity: 0, y: 10 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
          className="text-[#1a237e] text-2xl sm:text-3xl font-bold"
        >
          Types of Centrifuge Machines
        </motion.h1>
      </div>

      {/* Hero Image */}
      <div className="relative z-10 px-5 sm:px-8 pb-6 max-w-5xl mx-auto">
        <motion.div
          initial={{ opacity: 0, y: 15 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5, delay: 0.1 }}
          className="relative aspect-[16/9] rounded-2xl overflow-hidden shadow-lg"
        >
          <Image
            src="/images/centrifuge-types-hero.png"
            alt="Modern centrifuge machine in a professional laboratory setting"
            fill
            className="object-cover"
            sizes="90vw"
            priority
          />
        </motion.div>
      </div>

      {/* Introduction */}
      <motion.div
        initial={{ opacity: 0, y: 10 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.5, delay: 0.15 }}
        className="relative z-10 px-5 sm:px-8 pb-8 max-w-4xl mx-auto"
      >
        <div className="bg-blue-50/80 border-l-4 border-[#4169E1] rounded-r-lg p-4">
          <p className="text-black/80 text-sm sm:text-base leading-relaxed">
            A centrifuge is a laboratory or industrial device that uses rapid spinning motion to separate substances of different densities. When the rotor spins at high speed, centrifugal force pushes heavier particles outward while lighter substances remain closer to the center. Different types of centrifuges are designed for different applications, speeds, sample sizes, and specific laboratory or industrial needs.
          </p>
        </div>
      </motion.div>

      {/* All Types */}
      <div className="relative z-10 px-5 sm:px-8 pb-12 max-w-4xl mx-auto">
        {centrifugeTypes.map((type, index) => (
          <motion.div
            key={type.id}
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5, delay: 0.2 + index * 0.05 }}
            className="mb-10"
          >
            {/* Type Header */}
            <div className="flex items-center gap-3 mb-4">
              <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-[#1a237e] to-[#4169E1] flex items-center justify-center flex-shrink-0">
                <span className="text-white text-xs font-bold">{type.id}</span>
              </div>
              <h2 className="text-[#1a237e] text-lg sm:text-xl font-bold">{type.name}</h2>
            </div>

            {/* Image */}
            <div className="relative aspect-[16/9] rounded-2xl overflow-hidden shadow-md mb-5 bg-gray-50">
              <Image
                src={type.image}
                alt={type.imageAlt}
                fill
                className="object-cover"
                sizes="85vw"
              />
            </div>

            {/* Definition */}
            <div className={`${type.bgColor} border-l-4 ${type.borderColor} rounded-r-lg p-4 mb-4`}>
              <h3 className="text-[#1a237e] font-bold text-sm mb-2">Definition</h3>
              <p className="text-black/75 text-sm sm:text-base leading-relaxed">{type.definition}</p>
            </div>

            {/* How it Works */}
            <div className="bg-blue-50/80 border-l-4 border-[#4169E1] rounded-r-lg p-4 mb-4">
              <h3 className="text-[#1a237e] font-bold text-sm mb-2">How It Works</h3>
              <p className="text-black/75 text-sm sm:text-base leading-relaxed">{type.howItWorks}</p>
            </div>

            {/* Applications */}
            <div className="bg-purple-50/80 border-l-4 border-[#7C3AED] rounded-r-lg p-4 mb-4">
              <h3 className="text-[#7C3AED] font-bold text-sm mb-2">Applications</h3>
              <div className="space-y-1.5">
                {type.applications.map((app, i) => (
                  <div key={i} className="flex items-start gap-2">
                    <ChevronRight className="w-3 h-3 text-[#7C3AED] mt-1 flex-shrink-0" />
                    <span className="text-black/70 text-sm leading-relaxed">{app}</span>
                  </div>
                ))}
              </div>
            </div>

            {/* Advantages and Disadvantages */}
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              {/* Advantages */}
              <div className="bg-green-50/60 border-l-4 border-emerald-400 rounded-r-lg p-4">
                <h3 className="text-emerald-700 font-bold text-sm mb-2">Advantages</h3>
                <ul className="space-y-1.5">
                  {type.advantages.map((adv, i) => (
                    <li key={i} className="flex items-start gap-2">
                      <span className={`w-1.5 h-1.5 rounded-full ${type.dotColor} mt-1.5 flex-shrink-0`} />
                      <span className="text-black/70 text-xs sm:text-sm leading-relaxed">{adv}</span>
                    </li>
                  ))}
                </ul>
              </div>

              {/* Disadvantages */}
              <div className="bg-red-50/60 border-l-4 border-red-300 rounded-r-lg p-4">
                <h3 className="text-red-700 font-bold text-sm mb-2">Disadvantages</h3>
                <ul className="space-y-1.5">
                  {type.disadvantages.map((dis, i) => (
                    <li key={i} className="flex items-start gap-2">
                      <span className="w-1.5 h-1.5 rounded-full bg-red-400 mt-1.5 flex-shrink-0" />
                      <span className="text-black/70 text-xs sm:text-sm leading-relaxed">{dis}</span>
                    </li>
                  ))}
                </ul>
              </div>
            </div>

            {/* Divider (except last item) */}
            {index < centrifugeTypes.length - 1 && (
              <div className="h-px bg-gray-200 mt-10" />
            )}
          </motion.div>
        ))}

        {/* Closing Banner */}
        <motion.div
          initial={{ opacity: 0, y: 15 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5, delay: 0.7 }}
        >
          <div className="bg-gradient-to-r from-[#1a237e] to-[#4169E1] rounded-2xl p-5 sm:p-6 text-center">
            <p className="text-white/90 text-sm sm:text-base leading-relaxed">
              Centrifuges are essential equipment in many scientific and industrial applications. The right choice of centrifuge depends on factors such as speed requirements, sample volume, temperature control needs, and specific applications. Understanding the different types helps researchers and professionals select the most appropriate equipment for their needs.
            </p>
          </div>
        </motion.div>
      </div>

      {/* Bottom branding */}
      <div className="relative z-10 px-5 pb-6 text-center">
        <p className="text-black/20 text-[9px] tracking-widest uppercase">
          Centraas
        </p>
      </div>
    </div>
  );
}
