import Link from 'next/link';
import { BookOpen, ChevronRight, FlaskConical, RotateCcw, ShieldCheck } from 'lucide-react';

const glossaryItems = [
    { term: 'Absorbance', definition: 'The amount of light absorbed by atoms or molecules in a sample at a specific wavelength.', category: 'AAS' },
    { term: 'Atomization', definition: 'The conversion of a sample into free ground-state atoms, usually by flame or graphite furnace in AAS.', category: 'AAS' },
    { term: 'Beer-Lambert Law', definition: 'A relationship stating that absorbance is proportional to concentration, path length, and molar absorptivity.', category: 'AAS' },
    { term: 'Blank', definition: 'A sample containing all reagents except the analyte, used to correct background signal.', category: 'AAS' },
    { term: 'Calibration Curve', definition: 'A graph of instrument response against known standard concentrations, used to estimate unknown concentration.', category: 'AAS' },
    { term: 'Hollow Cathode Lamp', definition: 'An AAS light source that emits element-specific wavelengths for absorption measurement.', category: 'AAS' },
    { term: 'Monochromator', definition: 'An optical component that selects a narrow wavelength band for detection.', category: 'AAS' },
    { term: 'RCF', definition: 'Relative centrifugal force, the effective force generated by a centrifuge relative to gravity.', category: 'Centrifuge' },
    { term: 'RPM', definition: 'Revolutions per minute, the rotational speed of the centrifuge rotor.', category: 'Centrifuge' },
    { term: 'Rotor', definition: 'The rotating component of a centrifuge that holds sample tubes and generates separation force.', category: 'Centrifuge' },
    { term: 'Pellet', definition: 'The denser material that collects at the bottom or outer edge of a centrifuge tube after spinning.', category: 'Centrifuge' },
    { term: 'Supernatant', definition: 'The liquid layer remaining above the pellet after centrifugation.', category: 'Centrifuge' },
    { term: 'Density Gradient', definition: 'A separation method using layers of different densities to separate particles by buoyant density.', category: 'Centrifuge' },
    { term: 'PPE', definition: 'Personal protective equipment such as lab coat, gloves, goggles, and closed shoes.', category: 'Safety' },
    { term: 'SOP', definition: 'Standard Operating Procedure: an approved step-by-step instruction for safe and consistent work.', category: 'Safety' },
];

export default function GlossaryPage() {
    return (
        <div className="min-h-screen bg-gradient-to-b from-slate-50 via-blue-50 to-white">
            <div className="mx-auto max-w-5xl px-4 py-8 sm:px-6 lg:px-8">
                <div className="mb-6">
                    <Link href="/select-machine" className="inline-flex items-center gap-2 text-sm font-medium text-blue-700 hover:text-blue-900">
                        <ChevronRight className="h-4 w-4 rotate-180" />
                        Back to machine selection
                    </Link>
                </div>

                <div className="rounded-[2rem] bg-white p-6 shadow-sm ring-1 ring-slate-200 sm:p-8">
                    <div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between">
                        <div>
                            <div className="flex items-center gap-2 text-blue-700">
                                <BookOpen className="h-5 w-5" />
                                <p className="text-sm font-bold uppercase tracking-wide">Learning support</p>
                            </div>
                            <h1 className="mt-3 text-3xl font-bold tracking-tight text-slate-950 sm:text-4xl">
                                Centraas Glossary
                            </h1>
                            <p className="mt-3 max-w-3xl text-sm leading-relaxed text-slate-600 sm:text-base">
                                Quick definitions for important AAS, centrifuge, mathematics, chemistry, and laboratory safety terms used in this platform.
                            </p>
                        </div>
                        <div className="flex flex-wrap gap-2">
                            <span className="rounded-full bg-blue-50 px-3 py-1 text-xs font-semibold text-blue-700">AAS</span>
                            <span className="rounded-full bg-purple-50 px-3 py-1 text-xs font-semibold text-purple-700">Centrifuge</span>
                            <span className="rounded-full bg-amber-50 px-3 py-1 text-xs font-semibold text-amber-700">Safety</span>
                        </div>
                    </div>

                    <div className="mt-8 grid gap-3">
                        {glossaryItems.map((item) => (
                            <article key={item.term} className="rounded-2xl border border-slate-200 bg-slate-50 p-4 transition hover:border-blue-200 hover:bg-blue-50/60">
                                <div className="flex flex-col gap-2 sm:flex-row sm:items-start sm:justify-between">
                                    <h2 className="text-base font-bold text-slate-950">{item.term}</h2>
                                    <span className="w-fit rounded-full bg-white px-3 py-1 text-xs font-semibold text-slate-600 ring-1 ring-slate-200">
                                        {item.category}
                                    </span>
                                </div>
                                <p className="mt-2 text-sm leading-relaxed text-slate-700">{item.definition}</p>
                            </article>
                        ))}
                    </div>
                </div>

                <div className="mt-6 grid gap-4 md:grid-cols-3">
                    <Link href="/aas/overview" className="flex items-center justify-between rounded-2xl bg-white p-4 shadow-sm ring-1 ring-slate-200 hover:bg-blue-50">
                        <span className="flex items-center gap-2 text-sm font-semibold text-slate-800"><FlaskConical className="h-4 w-4" /> AAS overview</span>
                        <ChevronRight className="h-4 w-4 text-slate-400" />
                    </Link>
                    <Link href="/centrifuge/overview" className="flex items-center justify-between rounded-2xl bg-white p-4 shadow-sm ring-1 ring-slate-200 hover:bg-purple-50">
                        <span className="flex items-center gap-2 text-sm font-semibold text-slate-800"><RotateCcw className="h-4 w-4" /> Centrifuge overview</span>
                        <ChevronRight className="h-4 w-4 text-slate-400" />
                    </Link>
                    <Link href="/references" className="flex items-center justify-between rounded-2xl bg-white p-4 shadow-sm ring-1 ring-slate-200 hover:bg-amber-50">
                        <span className="flex items-center gap-2 text-sm font-semibold text-slate-800"><BookOpen className="h-4 w-4" /> References</span>
                        <ChevronRight className="h-4 w-4 text-slate-400" />
                    </Link>
                </div>

                <div className="mt-6 rounded-2xl border border-amber-200 bg-amber-50 p-4">
                    <div className="flex gap-2">
                        <ShieldCheck className="mt-0.5 h-5 w-5 shrink-0 text-amber-700" />
                        <p className="text-sm leading-relaxed text-amber-900">
                            Glossary terms support learning only. Always follow approved SOPs, manufacturer manuals, and qualified supervision during practical laboratory work.
                        </p>
                    </div>
                </div>
            </div>
        </div>
    );
}
